codehouseindia/Everything

Creating A Calculator Using Tkinter GUI.py
I have subscribed Code House Channel Thank You :-)
=> Python Tkinter GUI Calculator

Basic Html Form.html
I have subscribed your channel Code House
=> Creating a basic form by html

display_linked_list.c
Added a program to input elements and display them using linked list
=> Added a program to display  linked list

live_IPLscore_using Webscrapping.php
If you run this file in a server, you'll see live IPL score online on the screen
=> Added IPL_LIVE SCORE_Webscrapping.php

Code for 100!
Added new program for finding factorial of large no.
=> Added new program for finding factorial of large no.

Stark.py
(planets1_and_moon) Stark program
Gravitational system simulation using the
approximation method from Feynman-lectures,
p.9-8, using graphics.
Example: heavy central body, light planet,
very light moon!
Planet has a circular orbit, moon a stable
orbit around the planet.
You can hold the movement temporarily by
pressing the left mouse button with the
mouse over the scrollbar of the canvas.
=> Added the Stark program

Railways Announcement Software.py
For creating railway announcement software, we will be using a bunch of modules like pyaudio, pydub, and gTTS to process audio and get the announcing status of thousands of trains. By using PyAudio module, we can easily use Python to play and record audio on a variety of platforms. Pydub is a simple and well-designed Python module for audio manipulation and gTTS (which stands for Google Text-to-Speech) is a Python library and CLI tool to interface with Google Translate text-to-speech API.
=> Added the Railways Announcement Software program

Strange.py
Dancing turtle have a compound shape
consisting of a series of triangles of
decreasing size.
Turtles march along a circle while rotating
pairwise in opposite direction, with one
exception. Does that breaking of symmetry
enhance the attractiveness of the example?
Press any key to stop the animation.
Technically: demonstrates use of compound
shapes, transformation of shapes as well as
cloning turtles. The animation is
controlled through update().
=> Added the Strange program

pattern.c
=> Added a  pattern program

multi_matrix.m
=> added the matlab matrix program

Matrix multiplication in Java
created mulplication of matrices program in java language with user input
=> Create Matrix multiplication in Java

Perfect Number
Added a perfect number program.
=> Create Perfect Number

tries.cpp
C++ code to implement trie data structure.
=> Trie DataStructure

Odd_even_stonecoldanmol.c
=> Odd_even_stonecoldanmol.c

Canvasinhtml.html
=> Added a canvas animated program

ArmstrongNumber.java
Create a program to check given number is Armstrong number or not
=> Armstrong Number.java

BubbleSort.java
Created a program to Sort an array using Bubble Sort
=> BubbleSort.java

reverse a number
I had created a program to reverse a number in C++
=> Create reverse a number

Kotlin program to compare stringw
In the above program, we've two strings style 1 and style2. We simply use equality operator (==) to compare the two strings, which compares the value Bold to Bold and prints Equal.
=> Adding kotlin program to compare strings

the Fibonacci sequence
The Fibonacci sequence is the integer sequence where the first two terms are 0 and 1. After that, the next term is defined as the sum of the previous two terms.
=> The Fibonacci File

sieve of eratosthenes
=> Create sieve of eratosthenes

Program to reverse every word in a String using methods
Program to reverse every word in a String using methods
=> reverse string

face_recognitiion.py
This is face recognition program with openCV
=> face_recognition program 

rubyprogram.rb
=> rubyprogram.rb added

Binary Search.java
Adding Binary Search Implementation in Java
=> Adding Binary Search Implementation in Java

Atm program.c
PLEASE FIND MY ATTACHED C PROGRAM ON ATM MACHINE.
THANK YOU
=> Create Atm program.c

calculator using C
It contains sqrt, power, log function in addition to basic operations
=> Calculator using C

python program to check whether the no is odd or even
addded a new file for the new program to check whether the no uis odd or even
=> python program to check whether the no is odd or even

c++ inline function
=> added the c++ programa

Tetris using HTML
=> Create Tetris using HTML

Java program to check leap year
With this program you can check whether a year is leap year or not.
=> Create Java program to check leap year

design_print
To print Design. 
https://www.facebook.com/ishant.sinha.927/posts/1180522928990953
=> design_print

Snake using HTML
=> Create Snake using HTML

Event changer
Do check it out . it's a cool feature.
=> Added a new feature

NumberOfZeroes.cpp
This function returns the number of zeroes in n! for given n.
=> Added NumberOfZeroes

Positive Negative or Zero
A simple program to  check positive negative or zero
=> Positive Negative or Zero

simple promises chaining.js
=> promises chaining

FactLargeNo.c
You Can Find Factorial of any of the Number(upto 100000).
=> Factorial Of any of the Number

r2codes_palindrom.c
added my r2codes_palindrom.c file in your repo @codehouseindia
=> added my code for checking palindrome

intersection point of two linked list
Java program to get intersection point of two linked list
=> intersection point of two linked list

Window Sliding Technique
maximum sum of a subarray of size k
=> Window Sliding Technique

dart.login
Create form login in flutter part 1
=> form login 1

Complex2D.cpp
C++ Perform to a 2D FFT Inplace Given a Complex 2D Array
=> Complex2D.cpp

Solve_Qudratics.cpp
Solving Quadratic Equations using Factorisation( Shows SOLUTION
=> Solve_Qudratics.cpp

Templete.cpp
competitive programming Templete.cpp
=> Added Template.cpp

#https:/m.facebook.com/loops in c++, c++ recursion + Fibonacci, c++ recursion + fibonacci, nesting member function, operators in c++, tshirt
=> created new file

Check_externalIP.py
This is a simple python script to check external IP address you have. First we are importing the urllib and re modules.
=> To know the External IP adresss

Matrix Multiplication
program of matrix multiplication in C.
=> Create Matrix Multiplication

SAMPLE C PROGRAMMING CODE FOR BANK APPLICATION:
=> Create SAMPLE C PROGRAMMING CODE FOR BANK APPLICATION:

Linkedlist.cpp
This is a data-structure program for implementing Linked List.
=> LinkedList Program

UserAuthenticationExample.cpp
This is an example of a User Authentication Program using C++.
=> UserAuthenticationExample in C++

to find average in c
simple program for finding average of given numbers
=> to find average in c

Quadratic Primes.cpp
Here I have added the Quadratic Primes program using C++ programming language
=> Added Quadratic Primes

Chef and his characters.java
Adde Chef and his characters problem solution
=> Added Chef and his characters

User-Authentication-Process.cpp
=> Created User-Authentication-Process.cpp

Sum of array
correct my program if you find any error.
=> Sum of array elements using pointers

static data
correct program if you find any error.
=> Static data in file and read from file

size of Union
correct program if you find any error.
=> find the size of Union

calender.c
C program to display month by month calendar for a given year
=>  display month by month calendar for a given year

cycle.js
This is a sorting algorithm in JS, used to sorting items
=> Create this cycle.js

egg droping puzzle.c
This is a famous puzzle problem. Suppose there is a building with n floors, if we have m eggs, then how can we find the minimum number of drops needed to find a floor from which it is safe to drop an egg without breaking it.
There some important points to remember −
When an egg does not break from a given floor, then it will not break for any lower floor also.
If an egg breaks from a given floor, then it will break for all upper floors.
When an egg breaks, it must be discarded, otherwise we can use it again.
=> egg dropping puzzle

suscribe_and_share.html
=> suscribe_and_share.html

smaller number
to find a smaller no. in c programme
=> smaller no.

Quadratic Equation Program ( MIL )
Microprocessor code for dealing with quadratic equation
=> Quadratic Equation Program ( MIL )

Deployed site
=> html ,css and javascript

Student login page
=> Create Student login page

priority.c, scan.c
=> added new file

Matrix Addition
=> Matrix Addition

Percentage Calculator.c
please check once this code, this is very helpful for beginners
=> Create Percentage Calculator.c

To return all the Palindrome Words in a sentence
The user enters a sentence and the code returns whether a word in the string is palindrome or not
=> Create To return all the Palindrome Words in a sentence using JAVA

Nth Root of A Number
Code to return the Nth root of a number given by the user using C Language
=> Create Nth Root of A Number

Armstrong number C++
Do ya'll feel that there is an error ?
=> Create Armstrong number C++

Product of numbers in an array
A c++ program to find product of numbers from an array
=> Create Product of numbers in an array

Sum of numbers in an array
A c++ program to find the sum of numbers present in n size array
=> Create Sum of numbers in an array

Basic Calculator/Cal.css, Basic Calculator/Call.js, Basic Calculator/index.html
Creating Basic Calculator using Html for structure , CSS for design and JS for calculation .
=> Creating Basic Calculator

string permudation
to find different combinations of entered string
=> String Permudation

HCF of two numbers
=> Hcf of two numbers
